// Action constants
export const ADD_ASSIGNEES = 'add-assignees'
export const ADD_LABELS = 'add-labels'
export const ADD_REVIEWERS = 'add-reviewers'
export const CREATE_COMMENT = 'create-comment'
export const GREETING = 'greeting'
export const REMOVE_LABELS = 'remove-labels'
export const PR_NUMBER = 'pr-number'
export const MAINTAIN_COMMENT = 'maintain-comment'

// Variable constants
export const ASSIGNEES = 'assignees'
export const REVIEWERS = 'reviewers'
export const ACTIONS = 'actions'
export const DELIMITER = 'delimiter'
export const GREETING_MSG = 'greeting-message'
export const GREETING_GUIDELINE_ADDRESS = 'greeting-guideline-address'
export const LABELS_TO_ADD = 'labels-to-add'
export const LABELS_TO_REMOVE = 'labels-to-remove'
export const LABELS = 'labels'
export const LABEL_ONLY_IF = 'label-only-if'
export const REPO = 'repo'
export const COMMENT_BODY = 'comment-body'
export const BODY_FILTER = 'body-filter'
